# Generated by Django 4.2.20 on 2025-04-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0017_alter_familyhead_exact_nature_of_duties_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyhead',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
