# Generated by Django 4.2.20 on 2025-04-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0018_familyhead_updated_at_member_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyhead',
            name='landmark',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='landmark',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
